services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"  # Redis server port
      - "127.0.0.1:5540:8001"  # RedisInsight web interface
    volumes:
      - ./redis_data:/data     # Persistent storage